### ISSUE TITLE
print method for class tp.survtmle

### ISSUE THREAD

**Issue by nhejazi** [benkeser/survtmle#12]
It looks like the output for the class `tp.survtmle`, produced after a call to `timepoints` on an object created by the main `survtmle` function is a list of the point estimates and variance for the (two) groups at each time point considered.

This is rather hard to read, and a little overwhelming when the `tp.survtmle` object is simply examined. It appears that this could be organized into a `data.frame` (or `tibble`), organized / indexed by the time points, with the point estimates and variances as columns. (also, the variance matrices contain excess information...)

**Comment by benkeser** [comment]
Actually the output is a list of survtmle objects, which, when printed, show the estimates and (co-)variance estimates. I agree a print method would be good. Maybe we want to emulate what the print method for `cuminc` function in `cmprsk` package?

```r
install.packages(cmprsk)
n <- 100
T <- round(runif(n,1,20))
J <- rbinom(n,1,0.25) + rbinom(n,1,0.25)
fit <- cuminc(ftime = T, fstatus = J)
fit
# can look at how they choose what to print
print.cuminc
```

**Comment by nhejazi** [comment]
Got it. Thanks for pointing that out so quickly.

I like the idea of copying what `cmprsk::cuminc` does (or rather, their `print` method), since this might make the end-user comfortable with what the output looks like if they're already used to "standard" packages that provide cumulative incidence estimates.

**Comment by benkeser** [comment]
Agreed. I've modeled a lot of the structure and syntax around `cmprsk` so it makes sense to print things similarly too. Think you can handle cooking up a `print.timepoints` method?

**Comment by nhejazi** [comment]
Definitely, I'll take care of it.

**Comment by nhejazi** [comment]
`cmprsk::print.cuminc` for reference, copied from the [`cmprsk` package CRAN mirror on GitHub](https://github.com/cran/cmprsk):

```
print.cuminc <- function(x,ntp=4,maxtime,...) {
  if (!is.null(x$Tests)) {
  cat('Tests:\n')
  print(x$Tests)
  nc <- length(x)-1
  } else {
    nc <- length(x)
  }
  if (missing(maxtime)) {
    maxtime <- 0
    for (i in 1:nc) maxtime <- max(maxtime,x[[i]]$time)
  }
  tp <- pretty(c(0,maxtime),ntp+1)
  cat('Estimates and Variances:\n')
  print(timepoints(x,tp[-c(1,length(tp))]),...)
  invisible()
}
```

**Comment by nhejazi** [comment]
@benkeser -- I think you would have a quick answer to this, so here goes: Do we care about providing the full variance-covariance matrix at each timepoint in the print method for `tp.survtmle` objects? I ask because `cmprsk::cuminc` only the variance at given timepoints.

**Comment by nhejazi** [comment]
@benkeser, assuming my above comment about only including variances (dropping covariances) was correct, then the `print.tp.survtmle` functionality has been completed as of commit f1d4123.

Minimal example:
```
library(survtmle)
library(survival)
library(cmprsk)

set.seed(1234)
n <- 500
t_0 <- 5
trt <- rbinom(n, 1, 0.5)
adjustVars <- data.frame(W1 = round(runif(n)), W2 = round(runif(n, 0, 2)))

ftime <- round(runif(n, 0, 4)) + 1
ftype <- round(runif(n, 0, 1)) + round(runif(n, 0, 1))

suppressWarnings(
    fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt,
                     adjustVars = adjustVars, glm.trt = "1",
                     glm.ftime = paste0("trt + ",
                                        paste0("I(t==", seq_len(max(ftime)), ")",
                                               collapse = "+"), "+",
                                        paste0("I(trt*t==", seq_len(max(ftime)), ")",
                                               collapse = "+")),
                     glm.ctime = paste0("trt + ",
                                        paste0("I(t==", seq_len(max(ftime)), ")",
                                               collapse = "+"), "+",
                                        paste0("I(trt*t==", seq_len(max(ftime)), ")",
                                               collapse = "+")),
                     method = "hazard", t0 = t_0, returnModels = TRUE)
  )

suppressWarnings(
    tp.fit <- survtmle::timepoints(fit, times = seq_len(t_0))
  )
est.fit <- Reduce(cbind, lapply(tp.fit, "[[", "est"))

aj <- cuminc(ftime = ftime, fstatus = ftype, group = trt)
fit.aj <- cmprsk::timepoints(aj, seq_len(t_0))
```
```
print(tp.fit)
```

```
R > print(tp.fit)
$est
  ¦ ¦ ¦ ¦ ¦ t1         t2        t3        t4        t5
0 1 0.07407407 0.18781815 0.3633026 0.5014137 0.5819784
1 1 0.02723735 0.17056055 0.3192387 0.5566906 0.6614764
0 2 0.03703704 0.09601545 0.2051004 0.2971744 0.3978804
1 2 0.03501946 0.10463358 0.1603879 0.2412226 0.2936155

$var
  ¦ ¦ ¦ ¦ ¦ ¦ t1           t2           t3           t4          t5
0 1 0.0002822515 0.0006374195 0.0010411639 0.0012389022 0.001434104
1 1 0.0001467708 0.0003625570 0.0007332293 0.0010274235 0.001424615
0 2 0.0001030953 0.0005752224 0.0009517688 0.0011591301 0.001170775
1 2 0.0001314906 0.0003776751 0.0005744978 0.0008338186 0.001056870
```

```
print(fit.aj)
```

```
R > print(fit.aj)
$est
  ¦ ¦ ¦ ¦ ¦ ¦1          2         3         4         5
0 1 0.07407407 0.18781815 0.3633026 0.5014137 0.5819784
1 1 0.02723735 0.17056055 0.3192387 0.5566906 0.6614764
0 2 0.03703704 0.09601545 0.2051004 0.2971744 0.3978804
1 2 0.03501946 0.10463358 0.1603879 0.2412226 0.2936155

$var
  ¦ ¦ ¦ ¦ ¦ ¦ ¦1            2            3            4            5
0 1 0.0002834178 0.0006377865 0.0010304287 0.0011732775 0.0013001495
1 1 0.0001034980 0.0005767430 0.0009411790 0.0011180559 0.0010521626
0 2 0.0001473773 0.0003627966 0.0007257613 0.0009761190 0.0012890059
1 2 0.0001320043 0.0003787648 0.0005703853 0.0008110143 0.0009623972
```

__Clearly, the output of the `print.tp.survtmle` method now matches that of `print.cuminc` nearly exactly.__ Please try this out and close the issue if this solution is appropriate.

**Comment by benkeser** [comment]
Looks great. We're using different variance estimators than they are, so it's ok that the numbers are different.
