### ISSUE TITLE
development branch

### ISSUE THREAD

**Issue by benkeser** [benkeser/survtmle#13]
Once we reach a stable build that we're happy with, does it make sense to fast-forward the development branch to that point?

I think it'd then be a good idea to move a few functions over to the development branch (e.g., the cv_ functions and bin_ftime, as those are still in the works.

**Comment by nhejazi** [comment]
Definitely. As long as we won't be touching the `.R` files associated with those functions, I can fast-forward the development branch and then move them there.

Then, as we continue to make changes to the "stable" build on `master`, we can continue to just update that development branch (and it'll still be ahead, from the commits that added the cv_functions and bin_ftime), returning to it to work on those functions. We can then eventually add those to `master` when it's time for a subsequent CRAN release.

**Comment by nhejazi** [comment]
In-development functionality has been removed by 6886fca on branch `master` and re-added (after fast-forwarding of branch) by 40c4990 on branch `develop`.
