### ISSUE TITLE
Dimension error generated when creating DataList 

### ISSUE THREAD

**Issue by ernestatistics** [benkeser/survtmle#36]
Following up on the question in the one treatment case, I am creating a mock data set with one variable that has treatment = 0 and the rest has treatment = 1.

set.seed(1)
## simulate data
n <- 1000
t_0 <- 1
W <- data.frame(W1 = runif(n), W2 = rbinom(n, 1, 0.5))
x <- 1
A <- c(rep(0, x), rep(1, n-x))
ftype <- rbinom(n, size = 1, prob = 0.2)
ftime <- round(runif(n, 0.01, 3.15), 2)

Then when we call survtmle we get an error message 
## Run Survtmle
fit <- survtmle(ftime = ftime, ftype = ftype,
                trt = A, adjustVars = W,
                glm.trt = "1",
                glm.ftime = "W1 + W2",
                glm.ctime = "W1 + W2", 
                method = "hazard",
                t0 = t_0)

Or if you run 

fit <- survtmle(ftime = ftime, ftype = ftype,
                trt = A, adjustVars = W,
                glm.trt = "1",
                glm.ftime = "W1 + W2",
                glm.ctime = "W1 + W2", 
                method = "hazard",
                trtofInterest = 1,
                t0 = t_0)

it also gives the same error.

## Tracing the error

I think the error may be caused from the updateVariables() function on line 77:

dataList[[1]] <- merge( dataList[[1]], Reduce(rbind, dataList[2:(ntrt + 1)])[, c( "id", "t", "trt", "S.t", paste0(
          "F", ofInterestJ,".t"))], by = merge_vars)

so then the dataList[[1]] object has sum( dataList[[1]]$t == t_0) different than the size of the original data set, then when the routine runs the function getHazardInfluenceCurve()  in line 38 there is a problem with the dimensions of the data and the vector:
 
dat[[paste0("F", j, ".z", z, ".t0")]] <- dataList[[1]][[paste0("F", j, ".z", z, ".t0")]][dataList[[1]]$t == min(dataList[[1]]$t)]

**Comment by benkeser** [comment]
I looked into this a little bit and it's a complicated issue to work out. 

I would suggest instead removing `trtOfInterest = 1` from the call and making sure that you set `ftime = 1` and `ftype = 1` for the observation that you have with `trtOfInterest = 0`. It runs in that case.

**Comment by ernestatistics** [comment]
Yes, using those options worked for my application. Thanks David!
