### ISSUE TITLE
survtmle installation had a non-zero exit status

### ISSUE THREAD

**Issue by bricabrac23** [benkeser/survtmle#54]
I attempted to install a stable release of survtmle from GitHub via [devtools](https://www.rstudio.com/products/rpackages/devtools/) with:
devtools::install_github("benkeser/survtmle")

And this is the error I received:
<img width="935" alt="Screenshot 2023-02-28 at 13 08 48" src="https://user-images.githubusercontent.com/111821557/221977440-3a1d544b-dd46-4f66-9907-64c852ecc698.png">

I would prefer not to install an older version of R to have access to survtmle; what suggestions do you have to resolve this issue? Thank you very much in advance.

**Comment by benkeser** [comment]
Thanks, fixed in 9c7a60a

**Comment by bricabrac23** [comment]
It works for me now - thank you!
