### ISSUE TITLE
Unit tests that will be useful

### ISSUE THREAD

**Issue by benkeser** [benkeser/survtmle#8]
10 unit tests/things off the top of my head to check

~~1. I need to remind myself how makeDataList constructs the "time" column when there aren't failures at every time point.~~
The function now handles this case properly.

~~2. What happens when there are no events at t0?~~
 - ~~no events at all~~
 - ~~no events of one failure type~~
 - ~~no events in one trt arm~~
The function stops and requests that trt and ftype OfInterst be adjusted accordingly. 

~~3. How do we handle when W is constantly valued?~~
Compute unadjusted estimates

~~4. What happens if there's no censoring?~~
Handled internally by estimateCensoring

~~5. What happens if W is NULL?~~
Compute unadjusted estimates

~~6. How is mean.tmle handling very few events at t0? At some point I'd built in a check for a minimum number of events at the last time point. Is that still in there?~~
mean.tmle ignores super learner calls in number of events at t0 is <= 2. Instead it fits a glm adjusting only for treatment. If number of events is >2 but less than the default SuperLearner.CV.control()$V (currently V = 10), then it stratifies CV by outcome and uses number of events - 1 fold CV (i.e., one event guaranteed in each fold)

7. What happens if trt is constantly valued?

8. What happens if timepoints gets called for t = 1 and there are no events there? Does it check for a minimum number of events, I can't remember. 

9. Do things break if predicted hazards are close to 1?

~~10. What protections do we have against positivity violations? Should we consider adding a gtol option to truncate the smallest level of censoring (with warning when it's invoked?), as the tmle package does?~~
Feature has been added.

**Comment by nhejazi** [comment]
Re-opening so that we can use this list as a reference when fleshing out simple unit tests in the near future. We should shoot for ~50% coverage prior to CRAN submission.

**Comment by nhejazi** [comment]
Wow -- between the tests added in 2e56f07 and c0cdbcc, we already have >60% coverage!

**Comment by benkeser** [comment]
Yeah, not sure that they're exactly what Hadley had in mind for unit tests... They're rather big calls to survtmle, so if they break, it won't immediately be apparent why. Nevertheless, I think the tests I've written so far are useful checks on the functions.

**Comment by nhejazi** [comment]
Right -- the fact that we have such high coverage from just the two you put up is a great sign. Ideally, a unit test should tell you exactly what the error causing trouble is, so I can spend some time splitting them up into separate, smaller tests later. For now though, awesome that we've covered so much functionality with just those two larger calls.

**Comment by benkeser** [comment]
Probably not worth the effort on your part to split those tests up. It'd be more annoying then me spending 5 minutes debugging if things break.

**Comment by nhejazi** [comment]
Ok -- gotcha. Let's just leave things for now and revisit later if necessary.

**Comment by benkeser** [comment]
Added another test that should boost the coverage. I'm going to call it a night. Things are looking good!

**Comment by nhejazi** [comment]
Awesome! Thanks for taking care of this. We made quite a bit of progress today.

**Comment by benkeser** [comment]
Couldn't go to bed on a commit with an error that I authored!

**Comment by nhejazi** [comment]
Your commitment is astounding. Fixed now -- so, many thanks!

**Comment by benkeser** [comment]
The tests in tests/testthat/test-timepoints.R run locally on my machine, but fail on travis. @nhejazi , would you check whether you can get them to run on your machine?

**Comment by nhejazi** [comment]
All tests are passing locally on my Ubuntu 14.04 as of 866154c. It looks like there was a failing Travis-CI build last night related to this (on 939c0c9), but appears fixed now.

__^ignore this for now, re-running tests...__

**Comment by benkeser** [comment]
I've commented out the tests in test-timepoints.R to get rid of the errors. Try uncommenting and see.

**Comment by nhejazi** [comment]
Yea, I realized that right after I wrote that comment -- waiting on local `devtools::check` right now.

**Comment by nhejazi** [comment]
Output of `devtools::check` locally (on Ubuntu 14.04):
```
R CMD check results
1 error  | 0 warnings | 1 note 
checking tests ... ERROR
  Running ‘testthat.R’ [42s/26s]
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
         "J2")), t0 = 1L)
  6: checkInputs(ftime = ftime, ftype = ftype, trt = trt, t0 = t0, adjustVars = adjustVars, 
         SL.ftime = SL.ftime, SL.ctime = SL.ctime, SL.trt = SL.trt, glm.ftime = glm.ftime, 
         glm.ctime = glm.ctime, glm.trt = glm.trt, returnIC = returnIC, returnModels = returnModels, 
         ftypeOfInterest = ftypeOfInterest, trtOfInterest = trtOfInterest, bounds = bounds, 
         verbose = verbose, tol = tol, Gcomp = Gcomp, method = method)
  7: unique(trt)
  
  testthat results ================================================================
  OK: 15 SKIPPED: 0 FAILED: 2
  1. Error: hazard_tmle and mean_tmle timepoints equal kaplan-meier with no covariates (@test-timepoints.R#24) 
  2. Error: hazard_tmle and mean_tmle equal aalen-johansen with no covariates (@test-timepoints.R#63) 
  
  Error: testthat unit tests failed
  Execution halted
```

This matches the error from [this Travis-CI](https://travis-ci.org/benkeser/survtmle/jobs/250630056) build and [this Appveyor](https://ci.appveyor.com/project/benkeser/survtmle/build/1.0.97) build.

I'm not sure why it's passing on your end?

**Comment by benkeser** [comment]
Not sure. I'll work on it.

**Comment by nhejazi** [comment]
I'll try running it line-by-line in a little while to see whether I can catch it (in case you're not having luck finding it, fresh eyes might help...can be hard to debug code you wrote)

**Comment by benkeser** [comment]
I can't get the error to reproduce on an Ubuntu machine either. Passes when I run locally with this session info:
```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

Matrix products: default
BLAS/LAPACK: /app/easybuild/software/OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1/lib/libopenblas_prescottp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_1.0.2 survtmle_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11        magrittr_1.5        knitr_1.15.1       
 [4] devtools_1.12.0     nnls_1.4            munsell_0.4.3      
 [7] colorspace_1.3-2    lattice_0.20-35     R6_2.2.0           
[10] rlang_0.1.1         httr_1.2.1          plyr_1.8.4         
[13] tools_3.4.0         grid_3.4.0          gtable_0.2.0       
[16] SuperLearner_2.0-21 git2r_0.18.0        withr_1.0.2        
[19] lazyeval_0.2.0      digest_0.6.12       tibble_1.3.3       
[22] crayon_1.3.2        Matrix_1.2-10       ggplot2_2.2.1      
[25] tidyr_0.6.3         curl_2.5            memoise_1.1.0      
[28] compiler_3.4.0      scales_0.4.1       
```

**Comment by nhejazi** [comment]
Ok, thanks for that. I'm taking a look at it now and will report back when I have a fix.

**Comment by nhejazi** [comment]
Weird, `test-timepoints.R` runs perfectly fine by hand when I work through each section (as of commit 1787334), substituting `expect_equal` for `all.equal`...

Getting same error as before:

```
R CMD check results
1 error  | 0 warnings | 0 notes
checking tests ... ERROR
  Running ‘testthat.R’ [13s/13s]
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
         "J2")), t0 = 1L)
  6: checkInputs(ftime = ftime, ftype = ftype, trt = trt, t0 = t0, adjustVars = adjustVars,
         SL.ftime = SL.ftime, SL.ctime = SL.ctime, SL.trt = SL.trt, glm.ftime = glm.ftime,
         glm.ctime = glm.ctime, glm.trt = glm.trt, returnIC = returnIC, returnModels = returnModels,
         ftypeOfInterest = ftypeOfInterest, trtOfInterest = trtOfInterest, bounds = bounds,
         verbose = verbose, tol = tol, Gcomp = Gcomp, method = method)
  7: unique(trt)

  testthat results ================================================================
  OK: 15 SKIPPED: 0 FAILED: 2
  1. Error: hazard_tmle and mean_tmle timepoints equal Kaplan-Meier without covariates (@test-timepoints.R#34)
  2. Error: hazard_tmle and mean_tmle equal aalen-johansen with no covariates (@test-timepoints.R#85)

  Error: testthat unit tests failed
  Execution halted
```

Here's the output of `sessionInfo`:

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin16.5.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base

other attached packages:
 [1] cmprsk_2.2-7      survival_2.41-3   survtmle_0.1.0    dtplyr_0.0.2
 [5] data.table_1.10.4 dplyr_0.7.1       ggplot2_2.2.1     devtools_1.13.2
 [9] nima_0.4.0        colorout_1.1-2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11        compiler_3.4.0      plyr_1.8.4
 [4] bindr_0.1           tools_3.4.0         digest_0.6.12
 [7] memoise_1.1.0       tibble_1.3.3        gtable_0.2.0
[10] ProjectTemplate_0.7 lattice_0.20-35     pkgconfig_2.0.1
[13] rlang_0.1.1         Matrix_1.2-10       bindrcpp_0.2
[16] gridExtra_2.2.1     withr_1.0.2         SuperLearner_2.0-22
[19] gtools_3.5.0        grid_3.4.0          glue_1.1.1
[22] R6_2.2.2            tidyr_0.6.3         magrittr_1.5
[25] scales_0.4.1        ggthemes_3.4.0      nnls_1.4
[28] splines_3.4.0       assertthat_0.2.0    colorspace_1.3-2
[31] lazyeval_0.2.0      munsell_0.4.3
```

**Comment by nhejazi** [comment]
Might be related... https://github.com/hadley/testthat/issues/86

Use of `Sys.setenv("R_TESTS" = "")` might fix this.

**Comment by nhejazi** [comment]
With nearly 90% coverage and builds passing on Travis-CI and Appveyor, looks like it's about time to close this.
